/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as redirectSplatRouteImport } from './routes/(redirect)/$'
import { Route as AppLinksIndexRouteImport } from './routes/app/links/index'
import { Route as AppDomainsIndexRouteImport } from './routes/app/domains/index'
import { Route as AppAuthIndexRouteImport } from './routes/app/auth/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as AppLinksNewRouteImport } from './routes/app/links/new'
import { Route as AppAuthCallbackRouteImport } from './routes/app/auth/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const redirectSplatRoute = redirectSplatRouteImport.update({
  id: '/(redirect)/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLinksIndexRoute = AppLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthIndexRoute = AppAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLinksNewRoute = AppLinksNewRouteImport.update({
  id: '/links/new',
  path: '/links/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthCallbackRoute = AppAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/$': typeof redirectSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/auth/callback': typeof AppAuthCallbackRoute
  '/app/links/new': typeof AppLinksNewRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/auth/': typeof AppAuthIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/links/': typeof AppLinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof redirectSplatRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/auth/callback': typeof AppAuthCallbackRoute
  '/app/links/new': typeof AppLinksNewRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/auth': typeof AppAuthIndexRoute
  '/app/domains': typeof AppDomainsIndexRoute
  '/app/links': typeof AppLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/(redirect)/$': typeof redirectSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/auth/callback': typeof AppAuthCallbackRoute
  '/app/links/new': typeof AppLinksNewRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/auth/': typeof AppAuthIndexRoute
  '/app/domains/': typeof AppDomainsIndexRoute
  '/app/links/': typeof AppLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$'
    | '/app/'
    | '/api/auth/$'
    | '/app/auth/callback'
    | '/app/links/new'
    | '/app/analytics/'
    | '/app/auth/'
    | '/app/domains/'
    | '/app/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/app'
    | '/api/auth/$'
    | '/app/auth/callback'
    | '/app/links/new'
    | '/app/analytics'
    | '/app/auth'
    | '/app/domains'
    | '/app/links'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/(redirect)/$'
    | '/app/'
    | '/api/auth/$'
    | '/app/auth/callback'
    | '/app/links/new'
    | '/app/analytics/'
    | '/app/auth/'
    | '/app/domains/'
    | '/app/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  redirectSplatRoute: typeof redirectSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(redirect)/$': {
      id: '/(redirect)/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof redirectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/links/': {
      id: '/app/links/'
      path: '/links'
      fullPath: '/app/links/'
      preLoaderRoute: typeof AppLinksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/domains/': {
      id: '/app/domains/'
      path: '/domains'
      fullPath: '/app/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/auth/': {
      id: '/app/auth/'
      path: '/auth'
      fullPath: '/app/auth/'
      preLoaderRoute: typeof AppAuthIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/links/new': {
      id: '/app/links/new'
      path: '/links/new'
      fullPath: '/app/links/new'
      preLoaderRoute: typeof AppLinksNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/auth/callback': {
      id: '/app/auth/callback'
      path: '/auth/callback'
      fullPath: '/app/auth/callback'
      preLoaderRoute: typeof AppAuthCallbackRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthCallbackRoute: typeof AppAuthCallbackRoute
  AppLinksNewRoute: typeof AppLinksNewRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppAuthIndexRoute: typeof AppAuthIndexRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
  AppLinksIndexRoute: typeof AppLinksIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthCallbackRoute: AppAuthCallbackRoute,
  AppLinksNewRoute: AppLinksNewRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppAuthIndexRoute: AppAuthIndexRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
  AppLinksIndexRoute: AppLinksIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  redirectSplatRoute: redirectSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
