/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as redirectSplatRouteImport } from './routes/(redirect)/$'
import { Route as AppAppRouteRouteImport } from './routes/app/_app/route'
import { Route as AppAppIndexRouteImport } from './routes/app/_app/index'
import { Route as AppTemplatesPasswordRouteImport } from './routes/app/_templates/password'
import { Route as AppTemplatesExpiredRouteImport } from './routes/app/_templates/expired'
import { Route as AppAppLinksIndexRouteImport } from './routes/app/_app/links/index'
import { Route as AppAppDomainsIndexRouteImport } from './routes/app/_app/domains/index'
import { Route as AppAppAuthIndexRouteImport } from './routes/app/_app/auth/index'
import { Route as AppAppAnalyticsIndexRouteImport } from './routes/app/_app/analytics/index'
import { Route as AppAppLinksNewRouteImport } from './routes/app/_app/links/new'
import { Route as AppAppAuthCallbackRouteImport } from './routes/app/_app/auth/callback'
import { Route as AppAppLinksDomainSplatRouteImport } from './routes/app/_app/links/$domain.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const redirectSplatRoute = redirectSplatRouteImport.update({
  id: '/(redirect)/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRouteRoute = AppAppRouteRouteImport.update({
  id: '/app/_app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppTemplatesPasswordRoute = AppTemplatesPasswordRouteImport.update({
  id: '/app/_templates/password',
  path: '/app/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesExpiredRoute = AppTemplatesExpiredRouteImport.update({
  id: '/app/_templates/expired',
  path: '/app/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppLinksIndexRoute = AppAppLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppDomainsIndexRoute = AppAppDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppAuthIndexRoute = AppAppAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppAnalyticsIndexRoute = AppAppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppLinksNewRoute = AppAppLinksNewRouteImport.update({
  id: '/links/new',
  path: '/links/new',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppAuthCallbackRoute = AppAppAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppLinksDomainSplatRoute = AppAppLinksDomainSplatRouteImport.update({
  id: '/links/$domain/$',
  path: '/links/$domain/$',
  getParentRoute: () => AppAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRouteRouteWithChildren
  '/$': typeof redirectSplatRoute
  '/app/expired': typeof AppTemplatesExpiredRoute
  '/app/password': typeof AppTemplatesPasswordRoute
  '/app/': typeof AppAppIndexRoute
  '/app/auth/callback': typeof AppAppAuthCallbackRoute
  '/app/links/new': typeof AppAppLinksNewRoute
  '/app/analytics/': typeof AppAppAnalyticsIndexRoute
  '/app/auth/': typeof AppAppAuthIndexRoute
  '/app/domains/': typeof AppAppDomainsIndexRoute
  '/app/links/': typeof AppAppLinksIndexRoute
  '/app/links/$domain/$': typeof AppAppLinksDomainSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof redirectSplatRoute
  '/app/expired': typeof AppTemplatesExpiredRoute
  '/app/password': typeof AppTemplatesPasswordRoute
  '/app': typeof AppAppIndexRoute
  '/app/auth/callback': typeof AppAppAuthCallbackRoute
  '/app/links/new': typeof AppAppLinksNewRoute
  '/app/analytics': typeof AppAppAnalyticsIndexRoute
  '/app/auth': typeof AppAppAuthIndexRoute
  '/app/domains': typeof AppAppDomainsIndexRoute
  '/app/links': typeof AppAppLinksIndexRoute
  '/app/links/$domain/$': typeof AppAppLinksDomainSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_app': typeof AppAppRouteRouteWithChildren
  '/(redirect)/$': typeof redirectSplatRoute
  '/app/_templates/expired': typeof AppTemplatesExpiredRoute
  '/app/_templates/password': typeof AppTemplatesPasswordRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/app/_app/auth/callback': typeof AppAppAuthCallbackRoute
  '/app/_app/links/new': typeof AppAppLinksNewRoute
  '/app/_app/analytics/': typeof AppAppAnalyticsIndexRoute
  '/app/_app/auth/': typeof AppAppAuthIndexRoute
  '/app/_app/domains/': typeof AppAppDomainsIndexRoute
  '/app/_app/links/': typeof AppAppLinksIndexRoute
  '/app/_app/links/$domain/$': typeof AppAppLinksDomainSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$'
    | '/app/expired'
    | '/app/password'
    | '/app/'
    | '/app/auth/callback'
    | '/app/links/new'
    | '/app/analytics/'
    | '/app/auth/'
    | '/app/domains/'
    | '/app/links/'
    | '/app/links/$domain/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/app/expired'
    | '/app/password'
    | '/app'
    | '/app/auth/callback'
    | '/app/links/new'
    | '/app/analytics'
    | '/app/auth'
    | '/app/domains'
    | '/app/links'
    | '/app/links/$domain/$'
  id:
    | '__root__'
    | '/'
    | '/app/_app'
    | '/(redirect)/$'
    | '/app/_templates/expired'
    | '/app/_templates/password'
    | '/app/_app/'
    | '/app/_app/auth/callback'
    | '/app/_app/links/new'
    | '/app/_app/analytics/'
    | '/app/_app/auth/'
    | '/app/_app/domains/'
    | '/app/_app/links/'
    | '/app/_app/links/$domain/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppRouteRoute: typeof AppAppRouteRouteWithChildren
  redirectSplatRoute: typeof redirectSplatRoute
  AppTemplatesExpiredRoute: typeof AppTemplatesExpiredRoute
  AppTemplatesPasswordRoute: typeof AppTemplatesPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(redirect)/$': {
      id: '/(redirect)/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof redirectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_templates/password': {
      id: '/app/_templates/password'
      path: '/app/password'
      fullPath: '/app/password'
      preLoaderRoute: typeof AppTemplatesPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_templates/expired': {
      id: '/app/_templates/expired'
      path: '/app/expired'
      fullPath: '/app/expired'
      preLoaderRoute: typeof AppTemplatesExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app/links/': {
      id: '/app/_app/links/'
      path: '/links'
      fullPath: '/app/links/'
      preLoaderRoute: typeof AppAppLinksIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/domains/': {
      id: '/app/_app/domains/'
      path: '/domains'
      fullPath: '/app/domains/'
      preLoaderRoute: typeof AppAppDomainsIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/auth/': {
      id: '/app/_app/auth/'
      path: '/auth'
      fullPath: '/app/auth/'
      preLoaderRoute: typeof AppAppAuthIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/analytics/': {
      id: '/app/_app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAppAnalyticsIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/links/new': {
      id: '/app/_app/links/new'
      path: '/links/new'
      fullPath: '/app/links/new'
      preLoaderRoute: typeof AppAppLinksNewRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/auth/callback': {
      id: '/app/_app/auth/callback'
      path: '/auth/callback'
      fullPath: '/app/auth/callback'
      preLoaderRoute: typeof AppAppAuthCallbackRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/app/_app/links/$domain/$': {
      id: '/app/_app/links/$domain/$'
      path: '/links/$domain/$'
      fullPath: '/app/links/$domain/$'
      preLoaderRoute: typeof AppAppLinksDomainSplatRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
  }
}

interface AppAppRouteRouteChildren {
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppAuthCallbackRoute: typeof AppAppAuthCallbackRoute
  AppAppLinksNewRoute: typeof AppAppLinksNewRoute
  AppAppAnalyticsIndexRoute: typeof AppAppAnalyticsIndexRoute
  AppAppAuthIndexRoute: typeof AppAppAuthIndexRoute
  AppAppDomainsIndexRoute: typeof AppAppDomainsIndexRoute
  AppAppLinksIndexRoute: typeof AppAppLinksIndexRoute
  AppAppLinksDomainSplatRoute: typeof AppAppLinksDomainSplatRoute
}

const AppAppRouteRouteChildren: AppAppRouteRouteChildren = {
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppAuthCallbackRoute: AppAppAuthCallbackRoute,
  AppAppLinksNewRoute: AppAppLinksNewRoute,
  AppAppAnalyticsIndexRoute: AppAppAnalyticsIndexRoute,
  AppAppAuthIndexRoute: AppAppAuthIndexRoute,
  AppAppDomainsIndexRoute: AppAppDomainsIndexRoute,
  AppAppLinksIndexRoute: AppAppLinksIndexRoute,
  AppAppLinksDomainSplatRoute: AppAppLinksDomainSplatRoute,
}

const AppAppRouteRouteWithChildren = AppAppRouteRoute._addFileChildren(
  AppAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppRouteRoute: AppAppRouteRouteWithChildren,
  redirectSplatRoute: redirectSplatRoute,
  AppTemplatesExpiredRoute: AppTemplatesExpiredRoute,
  AppTemplatesPasswordRoute: AppTemplatesPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
